### PR TITLE
Download Directory Option

### PR DESCRIPTION
**Pull request by lkiesow**
This patch introduces a non-optional command line option to specify the
download directory.

### CODE REVIEW

**Comment by EmbeddedHenni** [comment]
get error during testing
`>>> r = search(download_dir='./test')
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
TypeError: search() got an unexpected keyword argument 'download_dir'`
have i did something wrong with the syntax?

**Comment by EmbeddedHenni** [comment]
this seems to work but i get http errors:
import sentinel5dl
r = sentinel5dl.search('./test')
Retrying failed HTTP request. (22, 'The requested URL returned error: 400 Bad Request')

**Comment by lkiesow** [comment]
You are trying to use `search(…)`.
You want to use `download(…)`.

**Comment by EmbeddedHenni** [comment]
ok thanks. working perfectly fine

**Pull request merged**
